




name: Build succeeds on PR

on: 
  pull_request: 
    branches: 
      - master

jobs: 
  build: 
    name: Build the project 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3  # this is for clone the github respository
        uses: actions/setup-node@v3 # install nodejs in machine 
        with: 
          node-version: '20'  # run npm in the machine 
      
      -name: Install Dependencies 
       run: npm install 

      -name: Run Build 
       run: npm run build  